/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const CharacterProfileView = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'followers' : IDL.Vec(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const CommentView = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'profileOwner' : IDL.Principal,
  'postId' : IDL.Text,
});
export const MessageView = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'conversationId' : IDL.Text,
  'timestamp' : IDL.Int,
  'profileOwner' : IDL.Principal,
});
export const ConversationView = IDL.Record({
  'id' : IDL.Text,
  'participants' : IDL.Vec(IDL.Text),
  'messages' : IDL.Vec(MessageView),
  'profileOwner' : IDL.Principal,
});
export const PostView = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'author' : IDL.Text,
  'likes' : IDL.Vec(IDL.Text),
  'timestamp' : IDL.Int,
  'image' : IDL.Opt(ExternalBlob),
  'profileOwner' : IDL.Principal,
});
export const StoryView = IDL.Record({
  'id' : IDL.Text,
  'author' : IDL.Text,
  'timestamp' : IDL.Int,
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'profileOwner' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCharacter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createConversation' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
  'createPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'createStory' : IDL.Func([IDL.Text, ExternalBlob, IDL.Text], [IDL.Text], []),
  'deleteCharacter' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'deleteStory' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacterProfiles' : IDL.Func(
      [],
      [IDL.Vec(CharacterProfileView)],
      ['query'],
    ),
  'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentView)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ConversationView)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
  'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'updateCharacter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'uploadAvatar' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const CharacterProfileView = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'followers' : IDL.Vec(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const CommentView = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'profileOwner' : IDL.Principal,
    'postId' : IDL.Text,
  });
  const MessageView = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'conversationId' : IDL.Text,
    'timestamp' : IDL.Int,
    'profileOwner' : IDL.Principal,
  });
  const ConversationView = IDL.Record({
    'id' : IDL.Text,
    'participants' : IDL.Vec(IDL.Text),
    'messages' : IDL.Vec(MessageView),
    'profileOwner' : IDL.Principal,
  });
  const PostView = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'author' : IDL.Text,
    'likes' : IDL.Vec(IDL.Text),
    'timestamp' : IDL.Int,
    'image' : IDL.Opt(ExternalBlob),
    'profileOwner' : IDL.Principal,
  });
  const StoryView = IDL.Record({
    'id' : IDL.Text,
    'author' : IDL.Text,
    'timestamp' : IDL.Int,
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'profileOwner' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCharacter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createComment' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createConversation' : IDL.Func([IDL.Vec(IDL.Text)], [IDL.Text], []),
    'createPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'createStory' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCharacter' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'deleteStory' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacterProfiles' : IDL.Func(
        [],
        [IDL.Vec(CharacterProfileView)],
        ['query'],
      ),
    'getComments' : IDL.Func([IDL.Text], [IDL.Vec(CommentView)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ConversationView)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(ConversationView)], ['query']),
    'getPosts' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(StoryView)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'updateCharacter' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'uploadAvatar' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };