/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CharacterProfileView {
  'id' : string,
  'bio' : string,
  'avatarTimestamp' : bigint,
  'owner' : Principal,
  'name' : string,
  'followers' : Array<string>,
  'avatar' : [] | [ExternalBlob],
}
export interface CommentView {
  'id' : string,
  'content' : string,
  'author' : string,
  'timestamp' : bigint,
  'profileOwner' : Principal,
  'postId' : string,
}
export interface ConversationView {
  'id' : string,
  'participants' : Array<string>,
  'messages' : Array<MessageView>,
  'profileOwner' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface MessageView {
  'id' : string,
  'content' : string,
  'sender' : string,
  'conversationId' : string,
  'timestamp' : bigint,
  'profileOwner' : Principal,
}
export interface PostView {
  'id' : string,
  'content' : string,
  'author' : string,
  'likes' : Array<string>,
  'timestamp' : bigint,
  'image' : [] | [ExternalBlob],
  'profileOwner' : Principal,
}
export interface StoryView {
  'id' : string,
  'author' : string,
  'timestamp' : bigint,
  'caption' : string,
  'image' : [] | [ExternalBlob],
  'profileOwner' : Principal,
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VideoView {
  'id' : string,
  'video' : ExternalBlob,
  'author' : string,
  'timestamp' : bigint,
  'caption' : string,
  'profileOwner' : Principal,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCharacter' : ActorMethod<[string, string], string>,
  'createComment' : ActorMethod<[string, string, string], string>,
  'createConversation' : ActorMethod<[Array<string>], string>,
  'createPost' : ActorMethod<[string, string, [] | [ExternalBlob]], string>,
  'createStory' : ActorMethod<[string, ExternalBlob, string], string>,
  'createVideo' : ActorMethod<[string, ExternalBlob, string], string>,
  'deleteCharacter' : ActorMethod<[string], undefined>,
  'deletePost' : ActorMethod<[string], undefined>,
  'deleteStory' : ActorMethod<[string], undefined>,
  'deleteVideo' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacterProfiles' : ActorMethod<[], Array<CharacterProfileView>>,
  'getComments' : ActorMethod<[string], Array<CommentView>>,
  'getConversation' : ActorMethod<[string], [] | [ConversationView]>,
  'getConversations' : ActorMethod<[], Array<ConversationView>>,
  'getPosts' : ActorMethod<[], Array<PostView>>,
  'getStories' : ActorMethod<[], Array<StoryView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVideos' : ActorMethod<[], Array<VideoView>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[string, string, string], string>,
  'updateCharacter' : ActorMethod<[string, string, string], undefined>,
  'uploadAvatar' : ActorMethod<[string, ExternalBlob], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];